### ISSUE TITLE
add 'byte[] to String' and 'String to byte[]' functions

### ISSUE THREAD

**Issue by hwaite** [wujikui/java-base-n-encodings#1]
Java provides bijective "byte[] java.util.Base64.Decoder.decode(String)" and "String java.util.Base64.Encoder.encodeToString(byte[])" methods. Would be convenient if your library offered something similar.

**Comment by wujikui** [comment]
As you kown, to encode/decode string, should be processing the character set. You can fork this project and implement functions for your requirements, or using wrapped helper methods.
Thanks for your advices.
